# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe2f6380e748bf17decb0b09e4d48e04b9e139cbcb27400104d20b6a323fe13bfaa4156529b1d33c8753008fa9f533f460eadcb1a8f1f101b17aab59fc30f76

test:
  secret_key_base: b4400a8aefc402a040962d6c23cb2eccbe76e83cfe1b1f6af2b5ac504e0f438caff7d87fe8f6deaae8a78ab2be2ca4087f993d86daa7bab4656ec39a5be01344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
